# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'client' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for client

pod 'Alamofire', '~> 5.0.0-rc.3'
pod 'DKImagePickerController'

end
